version: '3.8'

services:
  postgres_payload:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - payload_db_data:/var/lib/postgresql/data
    networks:
      - payload_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finn -d payload"]  # ‚Üê Add -d payload      interval: 10s
      timeout: 5s
      retries: 5

  payload:
    image: ghcr.io/finn-0b/payload:latest
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_payload:5432/${POSTGRES_DB}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      NEXT_PUBLIC_SERVER_URL: https://${DOMAIN_NAME}
      PORT: 3000
      HOSTNAME: "0.0.0.0"
    depends_on:
      postgres_payload:
        condition: service_healthy
    networks:
      - payload_network
      - web_network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - payload
    networks:
      - web_network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

networks:
  payload_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  payload_db_data:
  n8n_db_data: